
# List of CPP File #
LOCAL_SRC_FILES := main.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/AppDelegate.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/HelloWorldScene.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/Main/TTTBoard.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/Main/TTTBoardLogic.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/Main/TTTChess.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/Main/TTTMainScene.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/Main/TTTStyle.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/Main/TTTUILayer.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/SampleTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDData.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDHelper.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDMenu.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDMenuTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDSuite.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDSwitch.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/TDDLib/TDDTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/CocosStudioTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/ExampleTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/FontTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/TouchTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/TTTBoardLogicTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/TTTBoardTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/TTTChessTest.cpp
LOCAL_SRC_FILES += $(CLASS_PATH)/UnitTest/TTTUILayerTest.cpp


#Include DIR #
LOCAL_C_INCLUDES := $(LOCAL_PATH)/$(CLASS_PATH)
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/libs
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/Main
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/TDDLib
LOCAL_C_INCLUDES += $(LOCAL_PATH)/$(CLASS_PATH)/UnitTest
